Support ARM64 platform
NVIDIA/gdrcopy pull request #163
Opened 2021-01-20 07:13 UTC by pakmarkthub

Issue:
- See #63.

This PR:
- introduces GDRAPI_ARM64 definition.
- removes `tsc_khz` and `tm_cycles` when compiling on ARM64.
- marks (just a comment) `tm_cycles` and `cycles_per_ms` as deprecated in gdrdrv.h.

Presubmit testing:
- On gc11 (new gdrdrv with libgdrapi v2.1 and vice versa).
- On hpe-arm-07-01.

2021-01-20 21:27 UTC, drossetti requested changes

2021-01-20 23:01 UTC, drossetti commented
README.md should include a reference to Arm64 support where appropriate, for example:

> Developed and tested on RH7.x and Ubuntu18_04. The supported architectures are Linux x86_64 and ppc64le.

2021-01-21 01:43 UTC, pakmarkthub commented on src/gdrapi.c
> +        #ifndef GDRAPI_ARM64
As those two fields are available on all supported platforms, I just simply read from gdrdrv.

2021-01-21 01:44 UTC, pakmarkthub commented on src/gdrdrv/gdrdrv.c
> +    #include <linux/timex.h>
Fixed.

2021-01-21 01:44 UTC, pakmarkthub commented on src/gdrdrv/gdrdrv.c
> +    #ifndef CONFIG_ARM64
Fixed.

2021-01-21 01:44 UTC, pakmarkthub commented on src/gdrdrv/gdrdrv.c
> +    #endif
Fixed. We have `memset(0)` when creating mr.

2021-01-21 01:44 UTC, pakmarkthub commented on src/gdrdrv/gdrdrv.h
> +    #if !(defined(CONFIG_ARM64) || defined(GDRAPI_ARM64))
Fixed.

2021-01-21 01:49 UTC, pakmarkthub commented on src/gdrdrv/gdrdrv.c
> +    return pgprot_writecombine(old_prot);
Confirmed on linux kernel version 3 - 5. `pgprot_writecombine` is a macro. That macro uses only non-GPL symbols.

2021-01-21 02:33 UTC, pakmarkthub commented
> README.md should include a reference to Arm64 support where appropriate, for example:
> 
> > Developed and tested on RH7.x and Ubuntu18_04. The supported architectures are Linux x86_64 and ppc64le.

Updated.

@drossetti Can I ask you to re-review?

2021-01-21 22:03 UTC, drossetti approved these changes

2021-01-21 22:03 UTC, merged